method: oflow
data:
  path: data/Humans
  dataset: Humans
  input_type: pcl_seq
  classes: ['D-FAUST']
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  n_training_points: 512
  points_unpackbits: true
  n_training_pcl_points: 100
  input_pointcloud_n: 300
  input_pointcloud_noise: 0.001
  input_pointcloud_corresponding: true
  n_views: 24
  img_size: 224
  img_with_camera: false
  img_augment: false
  length_sequence: 17
  offset_sequence: 15
  n_files_per_sequence: -1
  points_file: points.npz
  mesh_seq_folder: mesh_seq
  points_iou_seq_folder: points_seq
  pointcloud_seq_folder: pcl_seq
  img_seq_folder: img
model:
  encoder: pointnet_resnet
  encoder_temporal: pointnet_resnet
  decoder: cbatchnorm
  velocity_field: concat
  encoder_latent: null
  encoder_latent_temporal: null
  decoder_kwargs: {}
  encoder_kwargs: {}
  encoder_latent_kwargs: {}
  encoder_temporal_kwargs: {}
  velocity_field_kwargs: {}
  encoder_latent_temporal_kwargs: {}
  learn_embedding: false
  ode_solver: dopri5
  ode_step_size: null
  use_adjoint: true
  rtol: 0.001
  atol: 0.00001
  vae_beta: 0.0001
  loss_corr: false
  loss_corr_bw: false
  loss_recon: true
  initialize_from: null
  initialization_file_name: model_best.pt
  c_dim: 512
  z_dim: 0
  use_camera: False
training:
  out_dir: out/00
  model_selection_metric: iou
  model_selection_mode: maximize
  n_eval_points: 5000
  batch_size: 16
  batch_size_vis: 1
  batch_size_val: 1
  print_every: 5
  visualize_every: 999999999
  checkpoint_every: 200
  validate_every: 2000
  backup_every: 100000
  eval_sample: true
  learning_rate: 0.0001
test:
  threshold: 0.3
  eval_mesh: true
  eval_pointcloud: false
  project_to_final_mesh: false
  eval_mesh_correspondences: true
  eval_mesh_iou: true
  eval_pointcloud_correspondences: true
  eval_only_end_time_steps: false
  model_file: model_best.pt
generation:
  generate_pointcloud: false
  generate_mesh: true
  resolution_0: 32
  upsampling_steps: 2
  refinement_step: 0
  simplify_nfaces: null
  padding: 0.1
  vis_n_outputs: 20
  n_time_steps: 17
  mesh_color: true
  interpolate: false
  correspondence: false
  only_end_time_points: false
  fix_z: false
  fix_zt: False
  shuffle_generation: true
  rand_seed: 12345
  batch_size: 1000000
  generation_dir: generation
  use_sampling: false
  copy_input: false
